//
//  ParsingRulesStore.swift
//  Airy
//
//  Stores GPT-generated parsing rules locally. Parser uses them without any API calls.
//

import Foundation

/// Rules generated by GPT for a specific OCR format. Applied locally.
struct ParsingRules: Codable, Equatable {
    /// Extra regex patterns for junk lines (e.g. "page 2", "order #12345")
    var extraJunkPatterns: [String]?
    /// Additional date regex patterns (Swift regex compatible)
    var datePatterns: [String]?
    /// Currency symbol → code mapping (e.g. "₽" → "RUB")
    var currencySymbols: [String: String]?
    /// Default currency when not detected (e.g. "USD", "RUB")
    var defaultCurrency: String?
    /// Optional custom amount regex
    var amountPattern: String?
}

final class ParsingRulesStore {
    static let shared = ParsingRulesStore()
    private let key = "parsingRules"
    private let lastOcrKey = "parsingRules_lastOcr"
    private let maxRulesets = 10
    /// Key: fingerprint of OCR format (first 300 chars hash). Value: rules.
    private var cache: [String: ParsingRules] = [:]
    private let queue = DispatchQueue(label: "parsingRulesStore")

    private init() {
        loadFromUserDefaults()
    }

    /// Save rules for OCR text. Computes fingerprint and also saves as global fallback.
    func saveForOcr(rules: ParsingRules, ocrText: String) {
        save(rules: rules, forFingerprint: fingerprint(ocrText))
        saveGlobal(rules: rules)
    }

    /// Save rules for a format. Fingerprint = hash of OCR prefix to detect same bank next time.
    func save(rules: ParsingRules, forFingerprint fingerprint: String) {
        queue.sync {
            cache[fingerprint] = rules
            persist()
        }
    }

    /// Save as "global" rules (single set, used when fingerprint unknown)
    func saveGlobal(rules: ParsingRules) {
        save(rules: rules, forFingerprint: "_global")
    }

    /// Lookup rules for this OCR. Returns best match or global rules.
    func rules(forOcrText ocrText: String) -> ParsingRules? {
        let fp = fingerprint(ocrText)
        return queue.sync {
            cache[fp] ?? cache["_global"]
        }
    }

    /// Merge GPT rules with built-in defaults. Returns merged rules to use.
    func mergedRules(forOcrText ocrText: String, builtIn: ParsingRules) -> ParsingRules {
        guard let custom = rules(forOcrText: ocrText) else { return builtIn }
        return ParsingRules(
            extraJunkPatterns: (builtIn.extraJunkPatterns ?? []) + (custom.extraJunkPatterns ?? []),
            datePatterns: (custom.datePatterns ?? []) + (builtIn.datePatterns ?? []),
            currencySymbols: (builtIn.currencySymbols ?? [:]).merging(custom.currencySymbols ?? [:]) { _, new in new },
            defaultCurrency: custom.defaultCurrency ?? builtIn.defaultCurrency,
            amountPattern: custom.amountPattern ?? builtIn.amountPattern
        )
    }

    func clearAll() {
        queue.sync {
            cache.removeAll()
            UserDefaults.standard.removeObject(forKey: key)
            UserDefaults.standard.removeObject(forKey: lastOcrKey)
        }
    }

    /// Last OCR from import. Used for "Generate rules from last import".
    var lastOcrSample: String? {
        get { UserDefaults.standard.string(forKey: lastOcrKey) }
        set { UserDefaults.standard.set(newValue, forKey: lastOcrKey) }
    }

    private func fingerprint(_ ocrText: String) -> String {
        let s = String(ocrText.prefix(300))
        var hash: UInt64 = 5381
        for c in s.utf8 {
            hash = ((hash << 5) &+ hash) &+ UInt64(c)
        }
        return String(hash)
    }

    private func persist() {
        let toSave = cache.mapValues { $0 }
        if let data = try? JSONEncoder().encode(toSave) {
            UserDefaults.standard.set(data, forKey: key)
        }
    }

    private func loadFromUserDefaults() {
        guard let data = UserDefaults.standard.data(forKey: key),
              let decoded = try? JSONDecoder().decode([String: ParsingRules].self, from: data) else { return }
        cache = decoded
    }
}
