//
//  ParsingRulesStore.swift
//  Airy
//
//  Stores GPT-generated parsing rule sets locally. Each set is separate (no mixing).
//  Parser tries each set in order; first non-empty valid result = 100% match, no GPT call.
//

import Foundation

/// Rules generated by GPT for a specific OCR format. Applied locally.
struct ParsingRules: Codable, Equatable {
    /// Extra regex patterns for junk lines (e.g. "page 2", "order #12345")
    var extraJunkPatterns: [String]?
    /// Additional date regex patterns (Swift regex compatible)
    var datePatterns: [String]?
    /// Currency symbol → code mapping (e.g. "₽" → "RUB")
    var currencySymbols: [String: String]?
    /// Default currency when not detected (e.g. "USD", "RUB")
    var defaultCurrency: String?
    /// Optional custom amount regex
    var amountPattern: String?
}

/// One rule set from one GPT response. Stored in order; tried in order.
struct RuleSetEntry: Codable, Equatable {
    let id: String
    let signature: String
    let rules: ParsingRules
}

final class ParsingRulesStore {
    static let shared = ParsingRulesStore()
    private let key = "parsingRuleSets"
    private let lastOcrKey = "parsingRules_lastOcr"
    private let imageCacheKey = "parsingRules_imageHashCache"
    private let maxRuleSets = 50
    private let maxImageCacheEntries = 100
    private var ruleSets: [RuleSetEntry] = []
    private var imageHashToItems: [String: [ParsedTransactionItem]] = [:]
    private let queue = DispatchQueue(label: "parsingRulesStore")

    private init() {
        loadFromUserDefaults()
        loadImageCache()
    }

    /// Return cached extraction for this image hash (same image → no GPT call).
    func cachedResult(forImageHash hash: String) -> [ParsedTransactionItem]? {
        queue.sync { imageHashToItems[hash] }
    }

    /// Store GPT extraction by image hash so the same image is not sent to GPT again.
    func cacheResult(_ items: [ParsedTransactionItem], forImageHash hash: String) {
        queue.sync {
            imageHashToItems[hash] = items
            if imageHashToItems.count > maxImageCacheEntries {
                let keysToRemove = Array(imageHashToItems.keys.prefix(imageHashToItems.count - maxImageCacheEntries))
                keysToRemove.forEach { imageHashToItems.removeValue(forKey: $0) }
            }
            persistImageCache()
        }
    }

    /// Append a new rule set (from a new GPT response or manual "Generate rules"). Does not merge with existing.
    func appendRuleSet(rules: ParsingRules, forOcrText ocrText: String) {
        saveForOcr(rules: rules, ocrText: ocrText)
    }

    /// Save rules for this OCR (appends a new rule set). Used by Settings "Generate rules" and by import GPT flow.
    func saveForOcr(rules: ParsingRules, ocrText: String) {
        queue.sync {
            let sig = fingerprint(ocrText)
            let entry = RuleSetEntry(id: UUID().uuidString, signature: sig, rules: rules)
            ruleSets.append(entry)
            if ruleSets.count > maxRuleSets {
                ruleSets.removeFirst(ruleSets.count - maxRuleSets)
            }
            persist()
        }
    }

    /// Try each rule set in order. Returns first non-empty valid parse result that also matches OCR content, or nil if none match.
    /// Rejects local results when amounts/dates don't appear in the text (e.g. same app, different page → wrong extraction).
    func tryMatch(ocrText: String, parser: LocalOCRParser, baseCurrency: String) -> [ParsedTransactionItem]? {
        queue.sync {
            for entry in ruleSets {
                let items = parser.parse(ocrText: ocrText, baseCurrency: baseCurrency, customRules: entry.rules)
                if isValidParseResult(items), parsedResultMatchesOcrText(items, ocrText: ocrText) {
                    return items
                }
            }
            return nil
        }
    }

    /// Last OCR from import. Used for "Generate rules from last import" in Settings.
    var lastOcrSample: String? {
        get { UserDefaults.standard.string(forKey: lastOcrKey) }
        set { UserDefaults.standard.set(newValue, forKey: lastOcrKey) }
    }

    func clearAll() {
        queue.sync {
            ruleSets.removeAll()
            imageHashToItems.removeAll()
            UserDefaults.standard.removeObject(forKey: key)
            UserDefaults.standard.removeObject(forKey: lastOcrKey)
            UserDefaults.standard.removeObject(forKey: imageCacheKey)
        }
    }

    private func isValidParseResult(_ items: [ParsedTransactionItem]) -> Bool {
        guard !items.isEmpty else { return false }
        for item in items {
            if item.amount < 0.01 || item.amount > 50_000 { return false }
            guard let y = Int(String(item.date.prefix(4))), (2020...2030).contains(y) else { return false }
            if (item.merchant?.count ?? 0) < 2 { return false }
        }
        return true
    }

    /// Only accept local parse if extracted amounts and dates appear in the OCR text (avoids wrong data when same layout, different content).
    private func parsedResultMatchesOcrText(_ items: [ParsedTransactionItem], ocrText: String) -> Bool {
        let normalized = ocrText.replacingOccurrences(of: ",", with: ".")
        for item in items {
            let amountStr = formatAmountForMatch(item.amount)
            if !amountAppearsInText(amountStr, ocrText: normalized) { return false }
            let year = String(item.date.prefix(4))
            if !normalized.contains(year) { return false }
            if item.date.count >= 10 {
                let day = String(item.date.suffix(2))
                if !normalized.contains(day) { return false }
            }
        }
        return true
    }

    private func formatAmountForMatch(_ amount: Double) -> (intPart: String, fracPart: String) {
        let intPart = Int(amount)
        let frac = Int(round((amount - Double(intPart)) * 100))
        return (String(intPart), frac > 0 ? String(frac) : "")
    }

    private func amountAppearsInText(_ amount: (intPart: String, fracPart: String), ocrText: String) -> Bool {
        guard ocrText.contains(amount.intPart) else { return false }
        if !amount.fracPart.isEmpty {
            if amount.fracPart.count == 1, !ocrText.contains(amount.fracPart) { return false }
            if amount.fracPart.count == 2, !ocrText.contains(amount.fracPart) { return false }
        }
        return true
    }

    private func fingerprint(_ ocrText: String) -> String {
        let s = String(ocrText.prefix(300))
        var hash: UInt64 = 5381
        for c in s.utf8 {
            hash = ((hash << 5) &+ hash) &+ UInt64(c)
        }
        return String(hash)
    }

    private func persist() {
        if let data = try? JSONEncoder().encode(ruleSets) {
            UserDefaults.standard.set(data, forKey: key)
        }
    }

    private func persistImageCache() {
        if let data = try? JSONEncoder().encode(imageHashToItems) {
            UserDefaults.standard.set(data, forKey: imageCacheKey)
        }
    }

    private func loadImageCache() {
        guard let data = UserDefaults.standard.data(forKey: imageCacheKey),
              let decoded = try? JSONDecoder().decode([String: [ParsedTransactionItem]].self, from: data) else { return }
        imageHashToItems = decoded
    }

    private func loadFromUserDefaults() {
        guard let data = UserDefaults.standard.data(forKey: key),
              let decoded = try? JSONDecoder().decode([RuleSetEntry].self, from: data) else { return }
        ruleSets = decoded
    }
}
